name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependências
      run: npm install

    - name: Build do React
      run: npm run build

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy para GCS
      run: |
        gsutil -m rsync -r -d build gs://${{ secrets.GCS_BUCKET_NAME }}
        gsutil -m setmeta -h "Cache-Control:no-cache,max-age=0" gs://${{ secrets.GCS_BUCKET_NAME }}/** 
